# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ACIS
version:      0.1
version_from: 
installdirs:  site
requires:
    AppConfig:                     1.52
    Carp::Assert:                  0.17
    CGI::Untaint:                  
    Proc::Daemon:                  0.03
    Storable:                      1.013
    XML::LibXSLT:                  
    XML::XPath:                    1.12

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
